"""
Web Interface for Article Generator

A simple web interface for the article generator using Flask.
"""

import os
import json
import logging
from flask import Flask, render_template, request, jsonify, send_from_directory
from app import OllamaProvider, ArticleGenerator, ArticleRequest, ArticleStyle, ArticleLength

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger("web_interface")

# Initialize Flask app
app = Flask(__name__)

# Initialize Ollama provider and article generator
provider = OllamaProvider()
generator = ArticleGenerator(provider)

# Cache for generated articles
article_cache = {}


@app.route('/')
def index():
    """Render the main page"""
    return render_template('index.html', 
                          models=generator.get_available_models(),
                          styles=[s.value for s in ArticleStyle],
                          lengths=[l.value for l in ArticleLength])


@app.route('/generate', methods=['POST'])
def generate_article():
    """Generate an article based on the request"""
    try:
        # Get JSON data from request
        data = request.get_json()
        if data is None:
            logger.error("No JSON data received in request")
            return jsonify({"error": "No JSON data received"}), 400
        
        # Extract parameters
        topic = data.get('topic', '')
        model_id = data.get('model', '')
        style_value = data.get('style', 'informative')
        length_value = data.get('length', 'medium')
        
        logger.info(f"Received request to generate article about '{topic}' using model '{model_id}'")

        # Validate parameters
        if not topic:
            return jsonify({"error": "Topic is required"}), 400
        
        if not model_id or model_id not in generator.get_available_models():
            return jsonify({"error": f"Invalid model. Choose from: {', '.join(generator.get_available_models())}"}), 400

        # Check cache
        cache_key = f"{model_id}:{style_value}:{length_value}:{topic}"
        if cache_key in article_cache:
            logger.info(f"Returning cached article for {cache_key}")
            return jsonify(article_cache[cache_key])
        
        # Create request
        style = ArticleStyle(style_value)
        length = ArticleLength(length_value)
        article_request = ArticleRequest(topic=topic, style=style, length=length)
        
        # Generate article
        response = generator._generate_with_memory_tracking(model_id, article_request)
        
        if response.error:
            return jsonify({"error": response.error}), 500
        
        # Prepare response
        result = {
            "article": response.article,
            "topic": response.topic,
            "style": response.style.value,
            "length": response.length.value,
            "model": response.model,
            "generation_time": response.generation_time,
            "tokens": response.tokens,
            "memory_usage": response.memory_usage,
            "analysis": response.analysis
        }
        
        # Cache the result
        article_cache[cache_key] = result
        
        return jsonify(result)
    
    except ValueError as e:
        logger.error(f"Value error: {str(e)}")
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        logger.exception("Error generating article")
        return jsonify({"error": str(e)}), 500


@app.route('/compare', methods=['POST'])
def compare_articles():
    """Compare articles generated by different models"""
    try:
        # Get JSON data from request
        data = request.get_json()
        if data is None:
            logger.error("No JSON data received in request")
            return jsonify({"error": "No JSON data received"}), 400
        
        # Extract parameters
        topic = data.get('topic', '')
        style_value = data.get('style', 'informative')
        length_value = data.get('length', 'medium')
        models = data.get('models', [])
        
        logger.info(f"Received request to compare models on topic: '{topic}'")
        
        # Validate parameters
        if not topic:
            return jsonify({"error": "Topic is required"}), 400
        
        if not models:
            models = generator.get_available_models()
        
        # Create request
        style = ArticleStyle(style_value)
        length = ArticleLength(length_value)
    except ValueError as e:
        logger.error(f"Value error: {str(e)}")
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        logger.exception("Error processing request")
        return jsonify({"error": f"Error processing request: {str(e)}"}), 500

    try:
        # Generate articles with each model
        results = []
        for model_id in models:
            if model_id not in generator.get_available_models():
                continue
            
            # Check cache
            cache_key = f"{model_id}:{style_value}:{length_value}:{topic}"
            if cache_key in article_cache:
                result = article_cache[cache_key]
            else:
                # Generate article
                article_req = ArticleRequest(topic=topic, style=style, length=length)
                response = generator._generate_with_memory_tracking(model_id, article_req)
                
                if response.error:
                    continue
                
                # Prepare result
                result = {
                    "model": model_id,
                    "article": response.article,
                    "generation_time": response.generation_time,
                    "tokens": response.tokens,
                    "memory_usage": response.memory_usage,
                    "analysis": response.analysis
                }
                
                # Cache the result
                article_cache[cache_key] = result
            
            results.append(result)
        
        if not results:
            return jsonify({"error": "No successful generations to compare"}), 500
        
        # Compare the results
        try:
            from text_analysis import compare_articles as compare_articles_func
            comparison = compare_articles_func(results)
            return jsonify({"results": results, "comparison": comparison})
        except ImportError:
            return jsonify({"results": results, "comparison": {"error": "Text analysis module not available"}})
    except Exception as e:
        logger.exception("Error comparing articles")
        return jsonify({"error": f"Error comparing articles: {str(e)}"}), 500


@app.route('/models')
def get_models():
    """Get available models"""
    return jsonify({"models": generator.get_available_models()})


@app.route('/styles')
def get_styles():
    """Get available styles"""
    return jsonify({"styles": [s.value for s in ArticleStyle]})


@app.route('/lengths')
def get_lengths():
    """Get available lengths"""
    return jsonify({"lengths": [l.value for l in ArticleLength]})


def create_templates():
    """Create template directory and files if they don't exist"""
    template_dir = os.path.join(os.path.dirname(__file__), 'templates')
    os.makedirs(template_dir, exist_ok=True)
    
    # Create index.html if it doesn't exist
    index_path = os.path.join(template_dir, 'index.html')
    if not os.path.exists(index_path):
        with open(index_path, 'w') as f:
            f.write("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Article Generator</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            max-width: 1200px;
            margin: 0 auto;
        }
        h1 {
            color: #333;
            text-align: center;
        }
        .container {
            display: flex;
            flex-wrap: wrap;
        }
        .controls {
            flex: 1;
            min-width: 300px;
            padding: 20px;
            background-color: #f5f5f5;
            border-radius: 5px;
        }
        .output {
            flex: 2;
            min-width: 500px;
            padding: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        input, select, textarea {
            width: 100%;
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #45a049;
        }
        .article {
            white-space: pre-wrap;
            background-color: #fff;
            border: 1px solid #ddd;
            padding: 20px;
            border-radius: 5px;
            margin-top: 20px;
        }
        .metrics {
            margin-top: 20px;
            padding: 10px;
            background-color: #f0f0f0;
            border-radius: 5px;
        }
        .loading {
            text-align: center;
            margin-top: 20px;
            display: none;
        }
        .spinner {
            border: 4px solid #f3f3f3;
            border-top: 4px solid #3498db;
            border-radius: 50%;
            width: 30px;
            height: 30px;
            animation: spin 2s linear infinite;
            margin: 0 auto;
        }
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        .tabs {
            display: flex;
            margin-bottom: 20px;
        }
        .tab {
            padding: 10px 20px;
            background-color: #ddd;
            cursor: pointer;
            border-radius: 5px 5px 0 0;
            margin-right: 5px;
        }
        .tab.active {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        .tab-content {
            display: none;
        }
        .tab-content.active {
            display: block;
        }
        .model-comparison {
            margin-top: 20px;
        }
        .model-card {
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 15px;
        }
        .model-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }
        .model-name {
            font-weight: bold;
            font-size: 18px;
        }
        .model-score {
            background-color: #4CAF50;
            color: white;
            padding: 5px 10px;
            border-radius: 15px;
        }
        .model-metrics {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            margin-bottom: 10px;
        }
        .metric {
            background-color: #f0f0f0;
            padding: 5px 10px;
            border-radius: 15px;
            font-size: 14px;
        }
        .model-content {
            max-height: 200px;
            overflow-y: auto;
            padding: 10px;
            background-color: #f9f9f9;
            border-radius: 5px;
            margin-top: 10px;
        }
        .expand-btn {
            background-color: #2196F3;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <h1>Article Generator</h1>
    
    <div class="tabs">
        <div class="tab active" data-tab="generate">Generate</div>
        <div class="tab" data-tab="compare">Compare Models</div>
    </div>
    
    <div class="tab-content active" id="generate-tab">
        <div class="container">
            <div class="controls">
                <div class="form-group">
                    <label for="topic">Topic:</label>
                    <input type="text" id="topic" placeholder="Enter article topic">
                </div>
                
                <div class="form-group">
                    <label for="model">Model:</label>
                    <select id="model">
                        {% for model in models %}
                        <option value="{{ model }}">{{ model }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="style">Style:</label>
                    <select id="style">
                        {% for style in styles %}
                        <option value="{{ style }}">{{ style }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="length">Length:</label>
                    <select id="length">
                        {% for length in lengths %}
                        <option value="{{ length }}">{{ length }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <button id="generate-btn">Generate Article</button>
            </div>
            
            <div class="output">
                <div class="loading">
                    <div class="spinner"></div>
                    <p>Generating article...</p>
                </div>
                
                <div id="article-container" style="display: none;">
                    <h2 id="article-topic"></h2>
                    <div class="article" id="article-content"></div>
                    
                    <div class="metrics">
                        <h3>Metrics</h3>
                        <p><strong>Generation Time:</strong> <span id="generation-time"></span> seconds</p>
                        <p><strong>Tokens:</strong> <span id="tokens"></span></p>
                        <p><strong>Memory Usage:</strong> <span id="memory-usage"></span> MB</p>
                        <p><strong>Quality Score:</strong> <span id="quality-score"></span>/100</p>
                        <p><strong>Structure Score:</strong> <span id="structure-score"></span>/100</p>
                        <p><strong>Readability Grade:</strong> <span id="readability-grade"></span></p>
                    </div>
                </div>
                
                <div id="error-container" style="display: none;">
                    <h3>Error</h3>
                    <p id="error-message" style="color: red;"></p>
                </div>
            </div>
        </div>
    </div>
    
    <div class="tab-content" id="compare-tab">
        <div class="container">
            <div class="controls">
                <div class="form-group">
                    <label for="compare-topic">Topic:</label>
                    <input type="text" id="compare-topic" placeholder="Enter article topic">
                </div>
                
                <div class="form-group">
                    <label for="compare-style">Style:</label>
                    <select id="compare-style">
                        {% for style in styles %}
                        <option value="{{ style }}">{{ style }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="compare-length">Length:</label>
                    <select id="compare-length">
                        {% for length in lengths %}
                        <option value="{{ length }}">{{ length }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="form-group">
                    <label>Models to Compare:</label>
                    <div id="model-checkboxes">
                        {% for model in models %}
                        <div>
                            <input type="checkbox" id="model-{{ model }}" value="{{ model }}" checked>
                            <label for="model-{{ model }}">{{ model }}</label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                
                <button id="compare-btn">Compare Models</button>
            </div>
            
            <div class="output">
                <div class="loading" id="compare-loading">
                    <div class="spinner"></div>
                    <p>Comparing models...</p>
                </div>
                
                <div id="comparison-container" style="display: none;">
                    <h2>Model Comparison Results</h2>
                    <p><strong>Topic:</strong> <span id="comparison-topic"></span></p>
                    
                    <div id="model-rankings"></div>
                    
                    <div class="model-comparison" id="model-comparison"></div>
                </div>
                
                <div id="compare-error-container" style="display: none;">
                    <h3>Error</h3>
                    <p id="compare-error-message" style="color: red;"></p>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        // Tab switching
        document.querySelectorAll('.tab').forEach(tab => {
            tab.addEventListener('click', () => {
                document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
                document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
                
                tab.classList.add('active');
                document.getElementById(`${tab.dataset.tab}-tab`).classList.add('active');
            });
        });
        
        // Generate article
        document.getElementById('generate-btn').addEventListener('click', async () => {
            const topic = document.getElementById('topic').value.trim();
            if (!topic) {
                alert('Please enter a topic');
                return;
            }
            
            const model = document.getElementById('model').value;
            const style = document.getElementById('style').value;
            const length = document.getElementById('length').value;
            
            // Show loading
            document.querySelector('.loading').style.display = 'block';
            document.getElementById('article-container').style.display = 'none';
            document.getElementById('error-container').style.display = 'none';
            
            try {
                const response = await fetch('/generate', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ topic, model, style, length })
                });
                
                const data = await response.json();
                
                if (response.ok) {
                    // Display article
                    document.getElementById('article-topic').textContent = data.topic;
                    document.getElementById('article-content').textContent = data.article;
                    document.getElementById('generation-time').textContent = data.generation_time.toFixed(2);
                    document.getElementById('tokens').textContent = data.tokens || 'N/A';
                    document.getElementById('memory-usage').textContent = data.memory_usage ? data.memory_usage.toFixed(2) : 'N/A';
                    
                    if (data.analysis) {
                        document.getElementById('quality-score').textContent = data.analysis.quality_score.toFixed(2);
                        document.getElementById('structure-score').textContent = data.analysis.structure_score.toFixed(2);
                        document.getElementById('readability-grade').textContent = data.analysis.readability_grade.toFixed(2);
                    } else {
                        document.getElementById('quality-score').textContent = 'N/A';
                        document.getElementById('structure-score').textContent = 'N/A';
                        document.getElementById('readability-grade').textContent = 'N/A';
                    }
                    
                    document.getElementById('article-container').style.display = 'block';
                } else {
                    // Display error
                    document.getElementById('error-message').textContent = data.error || 'An error occurred';
                    document.getElementById('error-container').style.display = 'block';
                }
            } catch (error) {
                document.getElementById('error-message').textContent = error.message;
                document.getElementById('error-container').style.display = 'block';
            } finally {
                document.querySelector('.loading').style.display = 'none';
            }
        });
        
        // Compare models
        document.getElementById('compare-btn').addEventListener('click', async () => {
            const topic = document.getElementById('compare-topic').value.trim();
            if (!topic) {
                alert('Please enter a topic');
                return;
            }
            
            const style = document.getElementById('compare-style').value;
            const length = document.getElementById('compare-length').value;
            
            // Get selected models
            const models = [];
            document.querySelectorAll('#model-checkboxes input:checked').forEach(checkbox => {
                models.push(checkbox.value);
            });
            
            if (models.length === 0) {
                alert('Please select at least one model');
                return;
            }
            
            // Show loading
            document.getElementById('compare-loading').style.display = 'block';
            document.getElementById('comparison-container').style.display = 'none';
            document.getElementById('compare-error-container').style.display = 'none';
            
            try {
                const response = await fetch('/compare', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ topic, style, length, models })
                });
                
                const data = await response.json();
                
                if (response.ok) {
                    // Display comparison results
                    document.getElementById('comparison-topic').textContent = topic;
                    
                    // Display rankings
                    const rankingsContainer = document.getElementById('model-rankings');
                    rankingsContainer.innerHTML = '<h3>Rankings</h3>';
                    
                    if (data.comparison && data.comparison.rankings) {
                        const rankingsList = document.createElement('ol');
                        data.comparison.rankings.forEach(rank => {
                            const item = document.createElement('li');
                            item.innerHTML = `<strong>${rank.model}</strong> - Score: ${rank.score.toFixed(2)}`;
                            rankingsList.appendChild(item);
                        });
                        rankingsContainer.appendChild(rankingsList);
                    }
                    
                    // Display model cards
                    const comparisonContainer = document.getElementById('model-comparison');
                    comparisonContainer.innerHTML = '';
                    
                    data.results.forEach(result => {
                        const modelCard = document.createElement('div');
                        modelCard.className = 'model-card';
                        
                        const analysis = result.analysis || {};
                        const qualityScore = analysis.quality_score || 0;
                        
                        modelCard.innerHTML = `
                            <div class="model-header">
                                <div class="model-name">${result.model}</div>
                                <div class="model-score">${qualityScore.toFixed(2)}/100</div>
                            </div>
                            <div class="model-metrics">
                                <div class="metric">Time: ${result.generation_time.toFixed(2)}s</div>
                                <div class="metric">Tokens: ${result.tokens || 'N/A'}</div>
                                <div class="metric">Memory: ${result.memory_usage ? result.memory_usage.toFixed(2) + ' MB' : 'N/A'}</div>
                                <div class="metric">Structure: ${analysis.structure_score ? analysis.structure_score.toFixed(2) + '/100' : 'N/A'}</div>
                                <div class="metric">Readability: ${analysis.readability_grade ? analysis.readability_grade.toFixed(2) : 'N/A'}</div>
                            </div>
                            <button class="expand-btn" onclick="toggleArticle(this)">Show Article</button>
                            <div class="model-content" style="display: none;">${result.article}</div>
                        `;
                        
                        comparisonContainer.appendChild(modelCard);
                    });
                    
                    document.getElementById('comparison-container').style.display = 'block';
                } else {
                    // Display error
                    document.getElementById('compare-error-message').textContent = data.error || 'An error occurred';
                    document.getElementById('compare-error-container').style.display = 'block';
                }
            } catch (error) {
                document.getElementById('compare-error-message').textContent = error.message;
                document.getElementById('compare-error-container').style.display = 'block';
            } finally {
                document.getElementById('compare-loading').style.display = 'none';
            }
        });
        
        // Toggle article visibility
        function toggleArticle(button) {
            const content = button.nextElementSibling;
            if (content.style.display === 'none') {
                content.style.display = 'block';
                button.textContent = 'Hide Article';
            } else {
                content.style.display = 'none';
                button.textContent = 'Show Article';
            }
        }
    </script>
</body>
</html>""")


if __name__ == "__main__":
    # Create templates
    create_templates()
    
    # Run the app
    app.run(debug=True, host='0.0.0.0', port=5000)
